# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 21:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_image', models.ImageField(blank=True, null=True, upload_to='artist_image/')),
                ('artist_banner', models.ImageField(blank=True, null=True, upload_to='artist_image/')),
                ('artist_bio', models.TextField(max_length=500)),
                ('artist_signature', models.CharField(max_length=70)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
