# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('name', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('artists', models.ManyToManyField(to='artists.Artists')),
            ],
        ),
    ]
