# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Crew')),
                ('artists', models.ManyToManyField(to='artists.Artists')),
            ],
        ),
    ]
